### ISSUE TITLE
Unexpected Behavior with Total Number of Signals

### ISSUE THREAD

**Issue by tyoungNIO** [nio-blocks/simulator#34]
Using the CounterIntervalSimulator block, with Total Number of Signals set to 1, the block will output two signals: the second signal is emitted at the time interval specified. Set to other values, including -1, it appears to work fine.

**Comment by mattdodge** [comment]
This sounds very similar to #27 that was closed. Can you confirm you are on the latest version of the block?

**Comment by hansmosh** [comment]
Yes, this has been fixed already. `util` has not been updated to use the newest simulator and I suspect that is the issue here.
