### ISSUE TITLE
Add Cron trigger to new framework

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/simulator#7]

**Comment by hansmosh** [comment]
@mattdodge How do you imagine the cron property will look on the block? Should we make something simple where you can just specify integers (and maybe have -1 be treated like *) or provide a string property and the config would be something like "0 0 * * *"?

**Comment by mattdodge** [comment]
I had originally thought it would just be a cron string but I like the idea of splitting it out. I think they are probably `StringProperty` properties though, rather than int. Cron stuff can sometimes be stringy things like commas and slashes
